//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IVNPayIPNPublishService", CallbackContract=typeof(IVNPayIPNPublishServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IVNPayIPNPublishService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVNPayIPNPublishService/Subscribe", ReplyAction="http://tempuri.org/IVNPayIPNPublishService/SubscribeResponse")]
    void Subscribe();
    
    [System.ServiceModel.OperationContractAttribute(IsTerminating=true, Action="http://tempuri.org/IVNPayIPNPublishService/Unsubscribe", ReplyAction="http://tempuri.org/IVNPayIPNPublishService/UnsubscribeResponse")]
    void Unsubscribe();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVNPayIPNPublishService/ResultTransChange", ReplyAction="http://tempuri.org/IVNPayIPNPublishService/ResultTransChangeResponse")]
    MDC.PaymentIntegration.VNPayIPNService.IPNResponse ResultTransChange(MDC.PaymentIntegration.VNPayIPNService.IPNRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IVNPayIPNPublishServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVNPayIPNPublishService/SubscribeResultTransChange")]
    void SubscribeResultTransChange(MDC.PaymentIntegration.VNPayIPNService.IPNRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IVNPayIPNPublishServiceChannel : IVNPayIPNPublishService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class VNPayIPNPublishServiceClient : System.ServiceModel.DuplexClientBase<IVNPayIPNPublishService>, IVNPayIPNPublishService
{
    
    public VNPayIPNPublishServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public VNPayIPNPublishServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public VNPayIPNPublishServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public VNPayIPNPublishServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public VNPayIPNPublishServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void Subscribe()
    {
        base.Channel.Subscribe();
    }
    
    public void Unsubscribe()
    {
        base.Channel.Unsubscribe();
    }
    
    public MDC.PaymentIntegration.VNPayIPNService.IPNResponse ResultTransChange(MDC.PaymentIntegration.VNPayIPNService.IPNRequest request)
    {
        return base.Channel.ResultTransChange(request);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IVNPayIPNService")]
public interface IVNPayIPNService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVNPayIPNService/GetResultTrans", ReplyAction="http://tempuri.org/IVNPayIPNService/GetResultTransResponse")]
    MDC.PaymentIntegration.VNPayIPNService.IPNResponse GetResultTrans(MDC.PaymentIntegration.VNPayIPNService.IPNRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IVNPayIPNServiceChannel : IVNPayIPNService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class VNPayIPNServiceClient : System.ServiceModel.ClientBase<IVNPayIPNService>, IVNPayIPNService
{
    
    public VNPayIPNServiceClient()
    {
    }
    
    public VNPayIPNServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public VNPayIPNServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VNPayIPNServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VNPayIPNServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public MDC.PaymentIntegration.VNPayIPNService.IPNResponse GetResultTrans(MDC.PaymentIntegration.VNPayIPNService.IPNRequest request)
    {
        return base.Channel.GetResultTrans(request);
    }
}
