//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDC.PaymentIntegration.VNPayIPNService
{
    using System.Runtime.Serialization;
 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IPNRequest", Namespace = "http://schemas.datacontract.org/2004/07/MDC.PaymentIntegration.VNPayIPNService")]
    public partial class IPNRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long amountField;
        
        private string bankCodeField;
        
        private string cardTypeField;
        
        private string checksumField;
        
        private string clientCodeField;
        
        private string clientRequestTimeField;
        
        private string clientTransactionCodeField;
        
        private string langField;
        
        private string merchantCodeField;
        
        private string methodCodeField;
        
        private string orderCodeField;
        
        private string orderDescriptionField;
        
        private string orderIdField;
        
        private string orderInforField;
        
        private string partnerCodeField;
        
        private string partnerTransactionCodeField;
        
        private string payDateField;
        
        private string psResponseTimeField;
        
        private string psTransactionCodeField;
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        private string serviceCodeField;
        
        private string terminalCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankCode
        {
            get
            {
                return this.bankCodeField;
            }
            set
            {
                this.bankCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cardType
        {
            get
            {
                return this.cardTypeField;
            }
            set
            {
                this.cardTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientCode
        {
            get
            {
                return this.clientCodeField;
            }
            set
            {
                this.clientCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientRequestTime
        {
            get
            {
                return this.clientRequestTimeField;
            }
            set
            {
                this.clientRequestTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientTransactionCode
        {
            get
            {
                return this.clientTransactionCodeField;
            }
            set
            {
                this.clientTransactionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchantCode
        {
            get
            {
                return this.merchantCodeField;
            }
            set
            {
                this.merchantCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string methodCode
        {
            get
            {
                return this.methodCodeField;
            }
            set
            {
                this.methodCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderCode
        {
            get
            {
                return this.orderCodeField;
            }
            set
            {
                this.orderCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderDescription
        {
            get
            {
                return this.orderDescriptionField;
            }
            set
            {
                this.orderDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderInfor
        {
            get
            {
                return this.orderInforField;
            }
            set
            {
                this.orderInforField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string partnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string partnerTransactionCode
        {
            get
            {
                return this.partnerTransactionCodeField;
            }
            set
            {
                this.partnerTransactionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payDate
        {
            get
            {
                return this.payDateField;
            }
            set
            {
                this.payDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psResponseTime
        {
            get
            {
                return this.psResponseTimeField;
            }
            set
            {
                this.psResponseTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psTransactionCode
        {
            get
            {
                return this.psTransactionCodeField;
            }
            set
            {
                this.psTransactionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serviceCode
        {
            get
            {
                return this.serviceCodeField;
            }
            set
            {
                this.serviceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string terminalCode
        {
            get
            {
                return this.terminalCodeField;
            }
            set
            {
                this.terminalCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IPNResponse", Namespace="http://schemas.datacontract.org/2004/07/MDC.PaymentIntegration.VNPayIPNService")]
    public partial class IPNResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private string messageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IVNPayIPNPublishService", CallbackContract=typeof(IVNPayIPNPublishServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IVNPayIPNPublishService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVNPayIPNPublishService/Subscribe", ReplyAction="http://tempuri.org/IVNPayIPNPublishService/SubscribeResponse")]
    void Subscribe();
    
    [System.ServiceModel.OperationContractAttribute(IsTerminating=true, Action="http://tempuri.org/IVNPayIPNPublishService/Unsubscribe", ReplyAction="http://tempuri.org/IVNPayIPNPublishService/UnsubscribeResponse")]
    void Unsubscribe();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVNPayIPNPublishService/ResultTransChange", ReplyAction="http://tempuri.org/IVNPayIPNPublishService/ResultTransChangeResponse")]
    MDC.PaymentIntegration.VNPayIPNService.IPNResponse ResultTransChange(MDC.PaymentIntegration.VNPayIPNService.IPNRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IVNPayIPNPublishServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVNPayIPNPublishService/SubscribeResultTransChange")]
    void SubscribeResultTransChange(MDC.PaymentIntegration.VNPayIPNService.IPNRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IVNPayIPNPublishServiceChannel : IVNPayIPNPublishService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class VNPayIPNPublishServiceClient : System.ServiceModel.DuplexClientBase<IVNPayIPNPublishService>, IVNPayIPNPublishService
{
    
    public VNPayIPNPublishServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public VNPayIPNPublishServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public VNPayIPNPublishServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public VNPayIPNPublishServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public VNPayIPNPublishServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void Subscribe()
    {
        base.Channel.Subscribe();
    }
    
    public void Unsubscribe()
    {
        base.Channel.Unsubscribe();
    }
    
    public MDC.PaymentIntegration.VNPayIPNService.IPNResponse ResultTransChange(MDC.PaymentIntegration.VNPayIPNService.IPNRequest request)
    {
        return base.Channel.ResultTransChange(request);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IVNPayIPNService")]
public interface IVNPayIPNService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVNPayIPNService/GetResultTrans", ReplyAction="http://tempuri.org/IVNPayIPNService/GetResultTransResponse")]
    MDC.PaymentIntegration.VNPayIPNService.IPNResponse GetResultTrans(MDC.PaymentIntegration.VNPayIPNService.IPNRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IVNPayIPNServiceChannel : IVNPayIPNService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class VNPayIPNServiceClient : System.ServiceModel.ClientBase<IVNPayIPNService>, IVNPayIPNService
{
    
    public VNPayIPNServiceClient()
    {
    }
    
    public VNPayIPNServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public VNPayIPNServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VNPayIPNServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VNPayIPNServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public MDC.PaymentIntegration.VNPayIPNService.IPNResponse GetResultTrans(MDC.PaymentIntegration.VNPayIPNService.IPNRequest request)
    {
        return base.Channel.GetResultTrans(request);
    }
}
